# Generated by Django 6.0.2 on 2026-03-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data_balance',
            field=models.IntegerField(default=1000),
        ),
    ]
